name: Feature request
description: Suggest an improvement to SWISSINNO Trap Card
title: "[Feature]: "
labels:
  - enhancement
body:
  - type: textarea
    id: use-case
    attributes:
      label: Use case
      description: What problem would this feature solve?
    validations:
      required: true
  - type: textarea
    id: proposal
    attributes:
      label: Proposed solution
    validations:
      required: true
  - type: textarea
    id: alternatives
    attributes:
      label: Alternatives considered

